[workspace]
members = [
    "crates/usfm3",
    "crates/usfm3-cli",
    "crates/usfm3-python",
    "crates/usfm3-wasm",
]
resolver = "3"

[workspace.dependencies]
usfm3 = { path = "crates/usfm3" }
logos = "0.15"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
quick-xml = { version = "0.37", features = ["serialize"] }
