[package]
name = "usfm3-wasm"
version = "0.1.3"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
usfm3 = { workspace = true }
wasm-bindgen = "0.2"
serde = { workspace = true }
serde_json = { workspace = true }
serde-wasm-bindgen = "0.6"
tsify-next = { version = "0.5", default-features = false, features = ["js"] }
